# Generated by Django 4.0.5 on 2022-07-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_remove_wishlistitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist'),
        ),
    ]
