# Generated by Django 4.0.5 on 2022-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(upload_to='media/photos/products'),
        ),
    ]
