# Generated by Django 4.0.5 on 2022-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_modified_at_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('New', 'New')], default='New', max_length=20),
        ),
    ]
